/**
 * Core tech / feature catalog — reclassified 22 ideas + foundational set.
 * Design-only items are not engine modules.
 */

import type { TechDef } from "./types";

const zeroRuntime = {
  cpu: 0.05,
  gpu: 0.05,
  memory: 0.05,
  storage: 0.05,
  io: 0.05,
  network: 0,
  battery: 0.05,
  thermal: 0.05,
};

function tech(partial: TechDef): TechDef {
  return partial;
}

/** Authoritative Part 2 feature/tech set (plus studio unlocks stay in RESEARCH). */
export const TECH_CATALOG: TechDef[] = [
  tech({
    id: "collectibles",
    name: "Collectibles",
    category: "game_design",
    description: "Exploration rewards and completionist hooks. Design content — not advanced tech.",
    era: "era1_foundational",
    tags: ["design", "content"],
    earliestYear: 1979,
    normalYear: 1979,
    latestYear: 2050,
    requires: [],
    researchRp: 0,
    researchCash: 0,
    researchWeeks: 0,
    prototypeRisk: 0,
    integrationWork: 0,
    productionWork: 40,
    runtime: zeroRuntime,
    maintenance: 0.05,
    debtGeneration: 0,
    genreRelevance: { action: 0.8, adventure: 0.9, rpg: 0.85, casual: 0.7 },
    sizeFit: { small: 1, medium: 1, large: 1, aaa: 1 },
    featureKey: "Collectibles",
    isDesignOnly: true,
    specialistField: "level",
  }),
  tech({
    id: "boss_encounters",
    name: "Boss Encounters",
    category: "game_design",
    description: "Set-piece fights. Highly relevant to Action/RPG; harmful when forced elsewhere.",
    era: "era1_foundational",
    tags: ["design", "combat"],
    earliestYear: 1979,
    normalYear: 1980,
    latestYear: 2050,
    requires: [],
    researchRp: 15,
    researchCash: 0,
    researchWeeks: 2,
    prototypeRisk: 0.1,
    integrationWork: 10,
    productionWork: 55,
    runtime: { ...zeroRuntime, cpu: 0.12 },
    maintenance: 0.08,
    debtGeneration: 2,
    genreRelevance: { action: 1, rpg: 0.95, adventure: 0.7, strategy: 0.35, casual: 0.3, simulation: 0.25 },
    sizeFit: { small: 0.9, medium: 1, large: 1, aaa: 1 },
    featureKey: "Boss Encounters",
    isDesignOnly: true,
    specialistField: "level",
  }),
  tech({
    id: "simple_quests",
    name: "Simple Quests",
    category: "narrative",
    description: "Basic objective tracking. Needs state tracking in engine for reliability.",
    era: "era1_foundational",
    tags: ["narrative"],
    earliestYear: 1980,
    normalYear: 1982,
    latestYear: 2050,
    requires: [],
    researchRp: 25,
    researchCash: 500,
    researchWeeks: 3,
    prototypeRisk: 0.12,
    integrationWork: 25,
    productionWork: 45,
    runtime: { ...zeroRuntime, cpu: 0.1, memory: 0.1 },
    maintenance: 0.1,
    debtGeneration: 3,
    genreRelevance: { adventure: 1, rpg: 1, action: 0.6, simulation: 0.5 },
    sizeFit: { small: 0.85, medium: 1, large: 1, aaa: 1 },
    featureKey: "Simple Quests",
    specialistField: "story",
  }),
  tech({
    id: "advanced_quests",
    name: "Advanced Quests",
    category: "narrative",
    description: "Branching narrative scripting tools — not just more text.",
    era: "era3_multimedia_3d",
    tags: ["narrative", "tools"],
    earliestYear: 1990,
    normalYear: 1992,
    latestYear: 2050,
    requires: ["simple_quests"],
    researchRp: 90,
    researchCash: 8000,
    researchWeeks: 6,
    prototypeRisk: 0.22,
    integrationWork: 70,
    productionWork: 90,
    runtime: { ...zeroRuntime, cpu: 0.18, memory: 0.2 },
    maintenance: 0.2,
    debtGeneration: 8,
    genreRelevance: { adventure: 1, rpg: 1, action: 0.5 },
    sizeFit: { small: 0.4, medium: 0.85, large: 1, aaa: 1 },
    featureKey: "Advanced Quests",
    specialistField: "story",
  }),
  tech({
    id: "cheat_codes",
    name: "Cheat Codes",
    category: "tools",
    description: "Internal testing aid; optional player secret. Does not auto-raise quality.",
    era: "era1_foundational",
    tags: ["tools"],
    earliestYear: 1979,
    normalYear: 1980,
    latestYear: 2050,
    requires: [],
    researchRp: 10,
    researchCash: 0,
    researchWeeks: 1,
    prototypeRisk: 0.05,
    integrationWork: 8,
    productionWork: 10,
    runtime: zeroRuntime,
    maintenance: 0.02,
    debtGeneration: 1,
    genreRelevance: { action: 0.7, casual: 0.6, rpg: 0.5 },
    sizeFit: { small: 1, medium: 1, large: 0.9, aaa: 0.7 },
    featureKey: "Cheat Codes",
    specialistField: "engine",
  }),
  tech({
    id: "language_settings",
    name: "Language Settings",
    category: "localization",
    description: "Localization pipeline foundation. Tiers expand over eras.",
    era: "era1_foundational",
    tags: ["localization"],
    earliestYear: 1979,
    normalYear: 1981,
    latestYear: 2050,
    requires: [],
    researchRp: 20,
    researchCash: 1000,
    researchWeeks: 2,
    prototypeRisk: 0.08,
    integrationWork: 20,
    productionWork: 35,
    runtime: { ...zeroRuntime, storage: 0.15 },
    maintenance: 0.12,
    debtGeneration: 2,
    genreRelevance: { adventure: 0.9, rpg: 0.9, casual: 0.8, action: 0.7 },
    sizeFit: { small: 0.8, medium: 1, large: 1, aaa: 1 },
    featureKey: "Language Settings",
    specialistField: "design",
  }),
  tech({
    id: "quick_save",
    name: "Quick Save",
    category: "save_system",
    description: "Reliable serialization and restore. Corruption risk if rushed.",
    era: "era2_advanced_2d",
    tags: ["save", "engine"],
    earliestYear: 1986,
    normalYear: 1989,
    latestYear: 2050,
    requires: [],
    researchRp: 45,
    researchCash: 2000,
    researchWeeks: 4,
    prototypeRisk: 0.2,
    integrationWork: 50,
    productionWork: 25,
    runtime: { ...zeroRuntime, memory: 0.15, storage: 0.2, io: 0.2 },
    maintenance: 0.18,
    debtGeneration: 6,
    genreRelevance: { adventure: 1, rpg: 1, simulation: 0.9, strategy: 0.85 },
    sizeFit: { small: 0.7, medium: 1, large: 1, aaa: 1 },
    featureKey: "Quick Save",
    specialistField: "engine",
  }),
  tech({
    id: "animated_textures",
    name: "Animated Textures",
    category: "rendering",
    description: "GPU/software render cost, memory, and asset work.",
    era: "era3_multimedia_3d",
    tags: ["graphics"],
    earliestYear: 1991,
    normalYear: 1994,
    latestYear: 2050,
    requires: [],
    researchRp: 55,
    researchCash: 4000,
    researchWeeks: 4,
    prototypeRisk: 0.15,
    integrationWork: 40,
    productionWork: 50,
    runtime: { ...zeroRuntime, gpu: 0.35, memory: 0.3 },
    maintenance: 0.12,
    debtGeneration: 5,
    genreRelevance: { action: 0.85, adventure: 0.8, rpg: 0.75, simulation: 0.7 },
    sizeFit: { small: 0.5, medium: 0.9, large: 1, aaa: 1 },
    featureKey: "Animated Textures",
    specialistField: "graphics",
  }),
  tech({
    id: "licensed_music",
    name: "Licensed Music",
    category: "business",
    description: "Legal licensing — not an engine module. Budget, rights, territories.",
    era: "era3_multimedia_3d",
    tags: ["legal", "audio", "business"],
    earliestYear: 1985,
    normalYear: 1992,
    latestYear: 2050,
    requires: [],
    researchRp: 30,
    researchCash: 15000,
    researchWeeks: 2,
    prototypeRisk: 0.05,
    integrationWork: 5,
    productionWork: 20,
    runtime: { ...zeroRuntime, storage: 0.25 },
    maintenance: 0.25,
    debtGeneration: 0,
    genreRelevance: { action: 0.7, casual: 0.8, adventure: 0.75 },
    sizeFit: { small: 0.4, medium: 0.8, large: 1, aaa: 1 },
    featureKey: "Licensed Music",
    isDesignOnly: true,
    specialistField: "sound",
  }),
  tech({
    id: "sampled_audio",
    name: "Sampled Audio",
    category: "audio",
    description: "First tier of realistic audio production.",
    era: "era3_multimedia_3d",
    tags: ["audio"],
    earliestYear: 1990,
    normalYear: 1993,
    latestYear: 2050,
    requires: [],
    researchRp: 50,
    researchCash: 5000,
    researchWeeks: 4,
    prototypeRisk: 0.12,
    integrationWork: 35,
    productionWork: 45,
    runtime: { ...zeroRuntime, memory: 0.25, storage: 0.3, cpu: 0.1 },
    maintenance: 0.1,
    debtGeneration: 4,
    genreRelevance: { action: 0.9, adventure: 0.85, rpg: 0.85, casual: 0.8 },
    sizeFit: { small: 0.6, medium: 1, large: 1, aaa: 1 },
    featureKey: "Sampled Audio",
    specialistField: "sound",
  }),
  tech({
    id: "spatial_audio",
    name: "Spatial Audio",
    category: "audio",
    description: "Environmental / occlusion / spatial presentation tier.",
    era: "era5_hd_digital",
    tags: ["audio"],
    earliestYear: 2002,
    normalYear: 2006,
    latestYear: 2050,
    requires: ["sampled_audio"],
    researchRp: 120,
    researchCash: 25000,
    researchWeeks: 7,
    prototypeRisk: 0.2,
    integrationWork: 80,
    productionWork: 70,
    runtime: { ...zeroRuntime, cpu: 0.25, memory: 0.2 },
    maintenance: 0.18,
    debtGeneration: 7,
    genreRelevance: { action: 1, adventure: 0.9, rpg: 0.85 },
    sizeFit: { small: 0.3, medium: 0.7, large: 1, aaa: 1 },
    featureKey: "Spatial Audio",
    specialistField: "sound",
  }),
  tech({
    id: "difficulty_selection",
    name: "Difficulty Selection",
    category: "game_design",
    description: "Player-facing difficulty options. Available early; respects accessibility.",
    era: "era1_foundational",
    tags: ["design", "accessibility"],
    earliestYear: 1979,
    normalYear: 1980,
    latestYear: 2050,
    requires: [],
    researchRp: 12,
    researchCash: 0,
    researchWeeks: 1,
    prototypeRisk: 0.05,
    integrationWork: 10,
    productionWork: 20,
    runtime: zeroRuntime,
    maintenance: 0.05,
    debtGeneration: 1,
    genreRelevance: { action: 0.9, rpg: 0.85, strategy: 0.9, casual: 0.75 },
    sizeFit: { small: 1, medium: 1, large: 1, aaa: 1 },
    featureKey: "Difficulty Selection",
    isDesignOnly: true,
    specialistField: "gameplay",
  }),
  tech({
    id: "adaptive_difficulty",
    name: "Adaptive Difficulty",
    category: "ai",
    description: "Telemetry-informed adaptation. Separate from static difficulty selection.",
    era: "era5_hd_digital",
    tags: ["ai", "telemetry"],
    earliestYear: 2000,
    normalYear: 2004,
    latestYear: 2050,
    requires: ["difficulty_selection"],
    researchRp: 100,
    researchCash: 18000,
    researchWeeks: 6,
    prototypeRisk: 0.25,
    integrationWork: 75,
    productionWork: 55,
    runtime: { ...zeroRuntime, cpu: 0.2, network: 0.1 },
    maintenance: 0.2,
    debtGeneration: 8,
    genreRelevance: { action: 0.95, casual: 0.85, rpg: 0.7 },
    sizeFit: { small: 0.4, medium: 0.85, large: 1, aaa: 1 },
    featureKey: "Adaptive Difficulty",
    specialistField: "ai",
  }),
  tech({
    id: "pattern_ai",
    name: "Pattern AI",
    category: "ai",
    description: "Classic scripted enemy patterns — foundation of the AI family.",
    era: "era1_foundational",
    tags: ["ai"],
    earliestYear: 1979,
    normalYear: 1980,
    latestYear: 2050,
    requires: [],
    researchRp: 20,
    researchCash: 0,
    researchWeeks: 2,
    prototypeRisk: 0.08,
    integrationWork: 15,
    productionWork: 30,
    runtime: { ...zeroRuntime, cpu: 0.15 },
    maintenance: 0.08,
    debtGeneration: 2,
    genreRelevance: { action: 1, strategy: 0.7, rpg: 0.75 },
    sizeFit: { small: 1, medium: 1, large: 1, aaa: 1 },
    featureKey: "Pattern AI",
    specialistField: "ai",
  }),
  tech({
    id: "pathfinding",
    name: "Pathfinding",
    category: "ai",
    description: "Navigation for agents. Different problem than pattern AI.",
    era: "era2_advanced_2d",
    tags: ["ai"],
    earliestYear: 1985,
    normalYear: 1988,
    latestYear: 2050,
    requires: ["pattern_ai"],
    researchRp: 60,
    researchCash: 3000,
    researchWeeks: 5,
    prototypeRisk: 0.18,
    integrationWork: 55,
    productionWork: 40,
    runtime: { ...zeroRuntime, cpu: 0.4, memory: 0.2 },
    maintenance: 0.15,
    debtGeneration: 6,
    genreRelevance: { strategy: 1, simulation: 0.95, action: 0.85, rpg: 0.8 },
    sizeFit: { small: 0.6, medium: 1, large: 1, aaa: 1 },
    featureKey: "Pathfinding",
    specialistField: "ai",
  }),
  tech({
    id: "behavior_trees",
    name: "Behavior Trees",
    category: "ai",
    description: "Composable agent decision structure for complex encounters.",
    era: "era5_hd_digital",
    tags: ["ai"],
    earliestYear: 2002,
    normalYear: 2005,
    latestYear: 2050,
    requires: ["pathfinding"],
    researchRp: 110,
    researchCash: 22000,
    researchWeeks: 7,
    prototypeRisk: 0.22,
    integrationWork: 85,
    productionWork: 60,
    runtime: { ...zeroRuntime, cpu: 0.35 },
    maintenance: 0.18,
    debtGeneration: 7,
    genreRelevance: { action: 0.95, rpg: 0.9, simulation: 0.85, strategy: 0.8 },
    sizeFit: { small: 0.3, medium: 0.75, large: 1, aaa: 1 },
    featureKey: "Behavior Trees",
    specialistField: "ai",
  }),
  tech({
    id: "realistic_water",
    name: "Realistic Water",
    category: "rendering",
    description: "Rendering + physics + world design. Critical for naval/sailing; useless for card menus.",
    era: "era4_accelerated",
    tags: ["graphics", "physics", "world"],
    earliestYear: 1996,
    normalYear: 1999,
    latestYear: 2050,
    requires: [],
    researchRp: 95,
    researchCash: 12000,
    researchWeeks: 6,
    prototypeRisk: 0.2,
    integrationWork: 70,
    productionWork: 65,
    runtime: { ...zeroRuntime, gpu: 0.45, cpu: 0.25, memory: 0.25 },
    maintenance: 0.16,
    debtGeneration: 7,
    genreRelevance: { simulation: 1, adventure: 0.85, action: 0.75, casual: 0.2, strategy: 0.35 },
    sizeFit: { small: 0.35, medium: 0.8, large: 1, aaa: 1 },
    featureKey: "Realistic Water",
    specialistField: "graphics",
  }),
  tech({
    id: "seasons",
    name: "Seasons",
    category: "simulation",
    description: "World time, weather, asset variants, save complexity.",
    era: "era5_hd_digital",
    tags: ["world", "simulation"],
    earliestYear: 1998,
    normalYear: 2003,
    latestYear: 2050,
    requires: [],
    researchRp: 100,
    researchCash: 16000,
    researchWeeks: 7,
    prototypeRisk: 0.24,
    integrationWork: 90,
    productionWork: 110,
    runtime: { ...zeroRuntime, cpu: 0.3, memory: 0.4, storage: 0.35 },
    maintenance: 0.25,
    debtGeneration: 12,
    genreRelevance: { simulation: 1, rpg: 0.9, adventure: 0.85, casual: 0.6 },
    sizeFit: { small: 0.25, medium: 0.7, large: 1, aaa: 1 },
    featureKey: "Seasons",
    specialistField: "world",
  }),
  tech({
    id: "advanced_shaders",
    name: "Advanced Shaders",
    category: "rendering",
    description: "Programmable graphics pipeline and materials.",
    era: "era5_hd_digital",
    tags: ["graphics"],
    earliestYear: 2001,
    normalYear: 2004,
    latestYear: 2050,
    requires: [],
    researchRp: 130,
    researchCash: 30000,
    researchWeeks: 8,
    prototypeRisk: 0.22,
    integrationWork: 100,
    productionWork: 75,
    runtime: { ...zeroRuntime, gpu: 0.55, memory: 0.3 },
    maintenance: 0.2,
    debtGeneration: 10,
    genreRelevance: { action: 0.95, adventure: 0.9, rpg: 0.85, simulation: 0.8 },
    sizeFit: { small: 0.25, medium: 0.7, large: 1, aaa: 1 },
    featureKey: "Advanced Shaders",
    specialistField: "graphics",
  }),
  tech({
    id: "realistic_plant_life",
    name: "Realistic Plant Life",
    category: "rendering",
    description: "LOD, instancing, wind, streaming — mid-2000s+ world tech.",
    era: "era6_live_ops",
    tags: ["graphics", "world"],
    earliestYear: 2004,
    normalYear: 2008,
    latestYear: 2050,
    requires: ["advanced_shaders"],
    researchRp: 140,
    researchCash: 35000,
    researchWeeks: 8,
    prototypeRisk: 0.25,
    integrationWork: 110,
    productionWork: 100,
    runtime: { ...zeroRuntime, gpu: 0.5, memory: 0.45, cpu: 0.25, io: 0.3 },
    maintenance: 0.22,
    debtGeneration: 11,
    genreRelevance: { adventure: 0.95, simulation: 0.95, rpg: 0.9, action: 0.75 },
    sizeFit: { small: 0.15, medium: 0.55, large: 1, aaa: 1 },
    featureKey: "Realistic Plant Life",
    specialistField: "world",
  }),
  tech({
    id: "realistic_particles",
    name: "Realistic Particles",
    category: "rendering",
    description: "Effects/physics particles. 'Realistic' describes execution quality, not free quality points.",
    era: "era5_hd_digital",
    tags: ["graphics", "effects"],
    earliestYear: 2003,
    normalYear: 2006,
    latestYear: 2050,
    requires: [],
    researchRp: 100,
    researchCash: 20000,
    researchWeeks: 6,
    prototypeRisk: 0.18,
    integrationWork: 70,
    productionWork: 55,
    runtime: { ...zeroRuntime, gpu: 0.4, cpu: 0.2 },
    maintenance: 0.15,
    debtGeneration: 6,
    genreRelevance: { action: 1, adventure: 0.8, simulation: 0.75 },
    sizeFit: { small: 0.4, medium: 0.85, large: 1, aaa: 1 },
    featureKey: "Realistic Particles",
    specialistField: "graphics",
  }),
  tech({
    id: "premium_content",
    name: "Premium Content Pipeline",
    category: "business",
    description: "DLC / expansions / season structure — business model, not gameplay engine module.",
    era: "era5_hd_digital",
    tags: ["business", "live"],
    earliestYear: 2004,
    normalYear: 2006,
    latestYear: 2050,
    requires: [],
    researchRp: 80,
    researchCash: 10000,
    researchWeeks: 4,
    prototypeRisk: 0.1,
    integrationWork: 30,
    productionWork: 40,
    runtime: { ...zeroRuntime, network: 0.2, storage: 0.15 },
    maintenance: 0.3,
    debtGeneration: 5,
    genreRelevance: { action: 0.8, rpg: 0.9, casual: 0.85 },
    sizeFit: { small: 0.2, medium: 0.7, large: 1, aaa: 1 },
    featureKey: "Premium Content",
    isDesignOnly: true,
    specialistField: "design",
  }),
  tech({
    id: "asset_bundling",
    name: "Asset Bundling",
    category: "optimization",
    description: "Swift-loading family: compression and packaging (not a magic load-time button).",
    era: "era3_multimedia_3d",
    tags: ["optimization", "io"],
    earliestYear: 1992,
    normalYear: 1995,
    latestYear: 2050,
    requires: [],
    researchRp: 55,
    researchCash: 4000,
    researchWeeks: 4,
    prototypeRisk: 0.12,
    integrationWork: 45,
    productionWork: 25,
    runtime: { ...zeroRuntime, cpu: 0.1, storage: 0.05, io: 0.05 },
    maintenance: 0.1,
    debtGeneration: 3,
    genreRelevance: { action: 0.8, adventure: 0.85, rpg: 0.9 },
    sizeFit: { small: 0.7, medium: 1, large: 1, aaa: 1 },
    featureKey: "Asset Bundling",
    specialistField: "engine",
  }),
  tech({
    id: "async_loading",
    name: "Asynchronous Loading",
    category: "optimization",
    description: "Background / async load pipeline — reduces hitching.",
    era: "era4_accelerated",
    tags: ["optimization"],
    earliestYear: 1998,
    normalYear: 2001,
    latestYear: 2050,
    requires: ["asset_bundling"],
    researchRp: 90,
    researchCash: 12000,
    researchWeeks: 6,
    prototypeRisk: 0.2,
    integrationWork: 80,
    productionWork: 35,
    runtime: { ...zeroRuntime, io: 0.1, cpu: 0.15 },
    maintenance: 0.15,
    debtGeneration: 6,
    genreRelevance: { action: 0.9, rpg: 0.95, adventure: 0.9 },
    sizeFit: { small: 0.5, medium: 0.9, large: 1, aaa: 1 },
    featureKey: "Async Loading",
    specialistField: "engine",
  }),
  tech({
    id: "basic_holograms",
    name: "Basic Holograms",
    category: "spatial",
    description: "Spatial/volumetric presentation. Requires future era + hardware.",
    era: "era9_spatial",
    tags: ["spatial", "graphics"],
    earliestYear: 2031,
    normalYear: 2034,
    latestYear: 2050,
    requires: ["advanced_shaders"],
    researchRp: 280,
    researchCash: 500000,
    researchWeeks: 14,
    prototypeRisk: 0.4,
    integrationWork: 200,
    productionWork: 150,
    runtime: { ...zeroRuntime, gpu: 0.9, cpu: 0.5, thermal: 0.6, battery: 0.5 },
    maintenance: 0.4,
    debtGeneration: 20,
    genreRelevance: { action: 0.8, adventure: 0.85, simulation: 0.9 },
    sizeFit: { small: 0.1, medium: 0.4, large: 0.8, aaa: 1 },
    featureKey: "Basic Holograms",
    specialistField: "graphics",
  }),
  tech({
    id: "advanced_holograms",
    name: "Advanced Holograms",
    category: "spatial",
    description: "Mature volumetric lighting and spatial simulation.",
    era: "era9_spatial",
    tags: ["spatial"],
    earliestYear: 2035,
    normalYear: 2037,
    latestYear: 2050,
    requires: ["basic_holograms"],
    researchRp: 360,
    researchCash: 900000,
    researchWeeks: 16,
    prototypeRisk: 0.45,
    integrationWork: 250,
    productionWork: 180,
    runtime: { ...zeroRuntime, gpu: 1.1, cpu: 0.6, thermal: 0.7 },
    maintenance: 0.45,
    debtGeneration: 25,
    genreRelevance: { action: 0.85, adventure: 0.9 },
    sizeFit: { large: 0.85, aaa: 1 },
    featureKey: "Advanced Holograms",
    specialistField: "graphics",
  }),
  tech({
    id: "interactive_holograms",
    name: "Interactive Holograms",
    category: "spatial",
    description: "Low-latency spatial interaction with environment understanding.",
    era: "era10_persistent",
    tags: ["spatial", "input"],
    earliestYear: 2041,
    normalYear: 2043,
    latestYear: 2050,
    requires: ["advanced_holograms"],
    researchRp: 450,
    researchCash: 2000000,
    researchWeeks: 20,
    prototypeRisk: 0.5,
    integrationWork: 300,
    productionWork: 220,
    runtime: { ...zeroRuntime, gpu: 1.2, cpu: 0.8, network: 0.4, thermal: 0.8 },
    maintenance: 0.5,
    debtGeneration: 30,
    genreRelevance: { simulation: 1, adventure: 0.95, action: 0.9 },
    sizeFit: { aaa: 1, large: 0.7 },
    featureKey: "Interactive Holograms",
    specialistField: "engine",
  }),
];

export const TECH_BY_ID: Record<string, TechDef> = Object.fromEntries(
  TECH_CATALOG.map((t) => [t.id, t]),
);

export function getTech(id: string): TechDef | undefined {
  return TECH_BY_ID[id];
}
