/** Canonical vanilla engine components — 27 total (1 start + 26 researchable). */
import type { EngineComponentDef } from "../types";

export const ENGINE_COMPONENTS: EngineComponentDef[] = [
  {
    id: "basic_2d_v1",
    name: "Basic 2D Graphics V1",
    category: "Graphics",
    starting: true,
    researchable: false,
    researchCost: 0,
    engineFeature: "Basic 2D Graphics V1",
  },
  {
    id: "2d_v2",
    name: "2D Graphics V2",
    category: "Graphics",
    starting: false,
    researchable: true,
    researchCost: 30,
    requires: ["basic_2d_v1"],
    engineFeature: "2D Graphics V2",
  },
  {
    id: "2d_v3",
    name: "2D Graphics V3",
    category: "Graphics",
    starting: false,
    researchable: true,
    researchCost: 35,
    requires: ["2d_v2"],
    engineFeature: "2D Graphics V3",
  },
  {
    id: "3d_v1",
    name: "3D Graphics V1",
    category: "Graphics",
    starting: false,
    researchable: true,
    researchCost: 40,
    requires: ["2d_v2"],
    engineFeature: "3D Graphics V1",
  },
  {
    id: "3d_v2",
    name: "3D Graphics V2",
    category: "Graphics",
    starting: false,
    researchable: true,
    researchCost: 45,
    requires: ["3d_v1"],
    engineFeature: "3D Graphics V2",
  },
  {
    id: "3d_v3",
    name: "3D Graphics V3",
    category: "Graphics",
    starting: false,
    researchable: true,
    researchCost: 50,
    requires: ["3d_v2"],
    engineFeature: "3D Graphics V3",
  },
  {
    id: "mono_sound",
    name: "Mono Sound",
    category: "Sound",
    starting: false,
    researchable: true,
    researchCost: 55,
    engineFeature: "Mono Sound",
  },
  {
    id: "stereo_sound",
    name: "Stereo Sound",
    category: "Sound",
    starting: false,
    researchable: true,
    researchCost: 60,
    requires: ["mono_sound"],
    engineFeature: "Stereo Sound",
  },
  {
    id: "surround_sound",
    name: "Surround Sound",
    category: "Sound",
    starting: false,
    researchable: true,
    researchCost: 65,
    requires: ["stereo_sound"],
    engineFeature: "Surround Sound",
  },
  {
    id: "save_game",
    name: "Save Game",
    category: "Engine",
    starting: false,
    researchable: true,
    researchCost: 70,
    engineFeature: "Save Game",
  },
  {
    id: "multiplayer",
    name: "Multiplayer",
    category: "Engine",
    starting: false,
    researchable: true,
    researchCost: 75,
    requires: ["save_game"],
    engineFeature: "Multiplayer",
  },
  {
    id: "online_play",
    name: "Online Play",
    category: "Engine",
    starting: false,
    researchable: true,
    researchCost: 80,
    requires: ["multiplayer"],
    engineFeature: "Online Play",
  },
  {
    id: "mod_support",
    name: "Mod Support",
    category: "Engine",
    starting: false,
    researchable: true,
    researchCost: 85,
    requires: ["save_game"],
    engineFeature: "Mod Support",
  },
  {
    id: "game_tutorials",
    name: "Game Tutorials",
    category: "Gameplay",
    starting: false,
    researchable: true,
    researchCost: 90,
    engineFeature: "Game Tutorials",
  },
  {
    id: "better_ux",
    name: "Better User Experience",
    category: "Gameplay",
    starting: false,
    researchable: true,
    researchCost: 95,
    requires: ["game_tutorials"],
    engineFeature: "Better User Experience",
  },
  {
    id: "achievements",
    name: "Achievements",
    category: "Gameplay",
    starting: false,
    researchable: true,
    researchCost: 100,
    engineFeature: "Achievements",
  },
  {
    id: "character_progression",
    name: "Character Progression",
    category: "Gameplay",
    starting: false,
    researchable: true,
    researchCost: 105,
    engineFeature: "Character Progression",
  },
  {
    id: "linear_story",
    name: "Linear Story",
    category: "Story and Quests",
    starting: false,
    researchable: true,
    researchCost: 110,
    engineFeature: "Linear Story",
  },
  {
    id: "simple_cutscenes",
    name: "Simple Cutscenes",
    category: "Story and Quests",
    starting: false,
    researchable: true,
    researchCost: 115,
    engineFeature: "Simple Cutscenes",
  },
  {
    id: "branching_story",
    name: "Branching Story",
    category: "Story and Quests",
    starting: false,
    researchable: true,
    researchCost: 120,
    requires: ["linear_story"],
    engineFeature: "Branching Story",
  },
  {
    id: "rich_backstory",
    name: "Rich Backstory",
    category: "Story and Quests",
    starting: false,
    researchable: true,
    researchCost: 125,
    requires: ["linear_story"],
    engineFeature: "Rich Backstory",
  },
  {
    id: "better_dialogues",
    name: "Better Dialogues",
    category: "Dialogue",
    starting: false,
    researchable: true,
    researchCost: 130,
    engineFeature: "Better Dialogues",
  },
  {
    id: "dialogue_tree",
    name: "Dialogue Tree",
    category: "Dialogue",
    starting: false,
    researchable: true,
    researchCost: 135,
    requires: ["better_dialogues"],
    engineFeature: "Dialogue Tree",
  },
  {
    id: "level_editor",
    name: "Level Editor",
    category: "Level Design",
    starting: false,
    researchable: true,
    researchCost: 140,
    engineFeature: "Level Editor",
  },
  {
    id: "better_ai",
    name: "Better AI",
    category: "Artificial Intelligence",
    starting: false,
    researchable: true,
    researchCost: 145,
    engineFeature: "Better AI",
  },
  {
    id: "advanced_ai",
    name: "Advanced AI",
    category: "Artificial Intelligence",
    starting: false,
    researchable: true,
    researchCost: 150,
    requires: ["better_ai"],
    engineFeature: "Advanced AI",
  },
  {
    id: "open_world",
    name: "Open World",
    category: "World Design",
    starting: false,
    researchable: true,
    researchCost: 155,
    engineFeature: "Open World",
  },
];

export const ENGINE_COMPONENT_COUNT = ENGINE_COMPONENTS.length;
export const STARTING_ENGINE_COMPONENT_ID = "basic_2d_v1";

export function startingEngineFeatures(): string[] {
  return ENGINE_COMPONENTS.filter((c) => c.starting).map((c) => c.engineFeature ?? c.name);
}

export function researchableEngineComponents() {
  return ENGINE_COMPONENTS.filter((c) => c.researchable);
}

