/** Canonical Phase One platform timeline — 40 fixed platforms + custom console. */
import type { PlatformDef } from "../types";

export const PLATFORMS: PlatformDef[] = [
  {
    id: "pc",
    name: "PC",
    short: "PC",
    year: 1982,
    era: "1980-1984",
    licenseCost: 0,
    marketSize: 0.85,
    techCeiling: 1.2,
    startUnlocked: true,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "great", strategy: "great", casual: "good" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "tes",
    name: "TES",
    short: "TES",
    year: 1983,
    era: "1980-1984",
    licenseCost: 8000,
    marketSize: 0.95,
    techCeiling: 0.7,
    startUnlocked: true,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "master_v",
    name: "Master V",
    short: "MV",
    year: 1982,
    era: "1980-1984",
    licenseCost: 10000,
    marketSize: 0.9,
    techCeiling: 0.72,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "commodore",
    name: "Commodore",
    short: "COM",
    year: 1982,
    era: "1980-1984",
    licenseCost: 0,
    marketSize: 1.1,
    techCeiling: 0.75,
    startUnlocked: true,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "ok", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "itara_5200",
    name: "Itara 5200",
    short: "I52",
    year: 1982,
    era: "1980-1984",
    licenseCost: 12000,
    marketSize: 0.7,
    techCeiling: 0.68,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "itara_backflash",
    name: "Itara Backflash",
    short: "IBF",
    year: 1983,
    era: "1980-1984",
    licenseCost: 15000,
    marketSize: 0.65,
    techCeiling: 0.7,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "gameling",
    name: "Gameling",
    short: "GL",
    year: 1989,
    era: "1985-1989",
    licenseCost: 25000,
    marketSize: 1.0,
    techCeiling: 0.78,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "vena_gear",
    name: "Vena Gear",
    short: "VG",
    year: 1988,
    era: "1985-1989",
    licenseCost: 30000,
    marketSize: 0.85,
    techCeiling: 0.82,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "vena_oasis",
    name: "Vena Oasis",
    short: "VO",
    year: 1986,
    era: "1985-1989",
    licenseCost: 28000,
    marketSize: 0.95,
    techCeiling: 0.85,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "super_tes",
    name: "Super TES",
    short: "STES",
    year: 1985,
    era: "1985-1989",
    licenseCost: 35000,
    marketSize: 1.15,
    techCeiling: 0.9,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "grapintosh",
    name: "Grapintosh",
    short: "GRP",
    year: 1987,
    era: "1985-1989",
    licenseCost: 0,
    marketSize: 0.55,
    techCeiling: 0.95,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "great", strategy: "great", casual: "good" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "grmac",
    name: "grMac",
    short: "gM",
    year: 1989,
    era: "1985-1989",
    licenseCost: 0,
    marketSize: 0.6,
    techCeiling: 1.0,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "great", strategy: "great", casual: "good" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem",
    name: "Playsystem",
    short: "PS",
    year: 1994,
    era: "1990-1994",
    licenseCost: 80000,
    marketSize: 1.25,
    techCeiling: 1.05,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "tes_64",
    name: "TES 64",
    short: "T64",
    year: 1993,
    era: "1990-1994",
    licenseCost: 70000,
    marketSize: 1.05,
    techCeiling: 1.0,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "gameling_color",
    name: "Gameling Color",
    short: "GLC",
    year: 1992,
    era: "1990-1994",
    licenseCost: 40000,
    marketSize: 0.95,
    techCeiling: 0.85,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "dreamvast",
    name: "DreamVast",
    short: "DV",
    year: 1999,
    era: "1995-1999",
    licenseCost: 100000,
    marketSize: 0.9,
    techCeiling: 1.1,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem_2",
    name: "Playsystem 2",
    short: "PS2",
    year: 1999,
    era: "1995-1999",
    licenseCost: 120000,
    marketSize: 1.4,
    techCeiling: 1.15,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mbox",
    name: "mBox",
    short: "mB",
    year: 1999,
    era: "1995-1999",
    licenseCost: 150000,
    marketSize: 1.2,
    techCeiling: 1.15,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "game_sphere",
    name: "Game Sphere",
    short: "GS",
    year: 1998,
    era: "1995-1999",
    licenseCost: 90000,
    marketSize: 1.0,
    techCeiling: 1.05,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "gs",
    name: "GS",
    short: "GS2",
    year: 2001,
    era: "2000-2004",
    licenseCost: 95000,
    marketSize: 1.05,
    techCeiling: 1.1,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "pps",
    name: "PPS",
    short: "PPS",
    year: 2004,
    era: "2000-2004",
    licenseCost: 110000,
    marketSize: 1.15,
    techCeiling: 1.12,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "nuu",
    name: "Nuu",
    short: "Nuu",
    year: 2004,
    era: "2000-2004",
    licenseCost: 100000,
    marketSize: 1.3,
    techCeiling: 1.0,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "3gs",
    name: "3GS",
    short: "3GS",
    year: 2003,
    era: "2000-2004",
    licenseCost: 85000,
    marketSize: 0.9,
    techCeiling: 0.95,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "2gs",
    name: "2GS",
    short: "2GS",
    year: 2004,
    era: "2000-2004",
    licenseCost: 70000,
    marketSize: 0.85,
    techCeiling: 0.9,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mbox_360",
    name: "mBox 360",
    short: "mB3",
    year: 2005,
    era: "2005-2009",
    licenseCost: 180000,
    marketSize: 1.3,
    techCeiling: 1.25,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem_3",
    name: "Playsystem 3",
    short: "PS3",
    year: 2006,
    era: "2005-2009",
    licenseCost: 200000,
    marketSize: 1.35,
    techCeiling: 1.3,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "grphone",
    name: "grPhone",
    short: "gPh",
    year: 2007,
    era: "2005-2009",
    licenseCost: 50000,
    marketSize: 1.2,
    techCeiling: 0.9,
    startUnlocked: false,
    genreAffinity: { action: "ok", adventure: "good", rpg: "ok", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "grpad",
    name: "grPad",
    short: "gPd",
    year: 2009,
    era: "2005-2009",
    licenseCost: 90000,
    marketSize: 1.4,
    techCeiling: 0.95,
    startUnlocked: false,
    genreAffinity: { action: "ok", adventure: "good", rpg: "ok", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "wuu",
    name: "Wuu",
    short: "Wuu",
    year: 2006,
    era: "2005-2009",
    licenseCost: 100000,
    marketSize: 1.25,
    techCeiling: 1.0,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "good", rpg: "good", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "viva_playsystem",
    name: "Viva Playsystem",
    short: "VPS",
    year: 2009,
    era: "2005-2009",
    licenseCost: 60000,
    marketSize: 0.7,
    techCeiling: 1.05,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem_2_slim",
    name: "Playsystem 2 Slim",
    short: "PS2S",
    year: 2005,
    era: "2005-2009",
    licenseCost: 80000,
    marketSize: 1.1,
    techCeiling: 1.12,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mbox_360_slim",
    name: "mBox 360 Slim",
    short: "mB3S",
    year: 2008,
    era: "2005-2009",
    licenseCost: 140000,
    marketSize: 1.15,
    techCeiling: 1.22,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mpad",
    name: "mPad",
    short: "mPd",
    year: 2012,
    era: "2010-2014",
    licenseCost: 95000,
    marketSize: 1.2,
    techCeiling: 1.0,
    startUnlocked: false,
    genreAffinity: { action: "ok", adventure: "good", rpg: "ok", simulation: "ok", strategy: "poor", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "oya",
    name: "OYA",
    short: "OYA",
    year: 2013,
    era: "2010-2014",
    licenseCost: 40000,
    marketSize: 0.4,
    techCeiling: 0.95,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mbox_one",
    name: "mBox One",
    short: "mBO",
    year: 2013,
    era: "2010-2014",
    licenseCost: 220000,
    marketSize: 1.25,
    techCeiling: 1.35,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem_4",
    name: "Playsystem 4",
    short: "PS4",
    year: 2013,
    era: "2010-2014",
    licenseCost: 230000,
    marketSize: 1.4,
    techCeiling: 1.4,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "swap",
    name: "Swap",
    short: "Swp",
    year: 2017,
    era: "2015-2019",
    licenseCost: 150000,
    marketSize: 1.35,
    techCeiling: 1.2,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "great", simulation: "ok", strategy: "good", casual: "great" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "mbox_next",
    name: "mBox Next",
    short: "mBN",
    year: 2020,
    era: "2020-Present",
    licenseCost: 250000,
    marketSize: 1.3,
    techCeiling: 1.5,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "playsystem_5",
    name: "Playsystem 5",
    short: "PS5",
    year: 2020,
    era: "2020-Present",
    licenseCost: 260000,
    marketSize: 1.4,
    techCeiling: 1.55,
    startUnlocked: false,
    genreAffinity: { action: "great", adventure: "great", rpg: "great", simulation: "good", strategy: "ok", casual: "ok" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
  {
    id: "holo_box",
    name: "Holo Box",
    short: "HB",
    year: 2021,
    era: "2020-Present",
    licenseCost: 280000,
    marketSize: 0.6,
    techCeiling: 1.6,
    startUnlocked: false,
    genreAffinity: { action: "good", adventure: "good", rpg: "good", simulation: "good", strategy: "ok", casual: "good" },
    audienceAffinity: { young: "good", everyone: "great", mature: "ok" },
  },
];

/** Player-created hardware — separate from timeline. */
export const CUSTOM_CONSOLE: PlatformDef = {
  id: "custom_console",
  name: "Custom Console",
  short: "CC",
  year: 9999,
  era: "Special",
  licenseCost: 0,
  marketSize: 0.8,
  techCeiling: 1.4,
  isCustom: true,
  genreAffinity: { action: "good", adventure: "good", rpg: "good", simulation: "good", strategy: "good", casual: "good" },
  audienceAffinity: { young: "good", everyone: "great", mature: "good" },
};

export const PLATFORM_COUNT = PLATFORMS.length;

export function getPlatformDef(id: string): PlatformDef | undefined {
  if (id === CUSTOM_CONSOLE.id) return CUSTOM_CONSOLE;
  return PLATFORMS.find((p) => p.id === id);
}

export function platformsAvailableInYear(year: number, unlocked: string[]): PlatformDef[] {
  return PLATFORMS.filter(
    (p) => p.year <= year && (p.startUnlocked || unlocked.includes(p.id) || p.licenseCost === 0),
  );
}

