/** Canonical Phase One topic catalog — 132 unique topics, 6 genres each. */
import type { CompatibilityValue, GenreId, TopicDef } from "../types";

const V = { E: 100, S: 85, G: 70, W: 55, K: 35, B: 15 } as const;

function c(
  ranks: [GenreId, GenreId, GenreId, GenreId, GenreId, GenreId],
): Record<GenreId, CompatibilityValue> {
  const vals: CompatibilityValue[] = [100, 85, 70, 55, 35, 15];
  return {
    action: vals[ranks.indexOf("action")]!,
    adventure: vals[ranks.indexOf("adventure")]!,
    rpg: vals[ranks.indexOf("rpg")]!,
    simulation: vals[ranks.indexOf("simulation")]!,
    strategy: vals[ranks.indexOf("strategy")]!,
    casual: vals[ranks.indexOf("casual")]!,
  };
}

function t(
  id: string,
  name: string,
  homeGenre: GenreId,
  ranks: [GenreId, GenreId, GenreId, GenreId, GenreId, GenreId],
  /** Research provenance only — never player-facing pack framing. All topics are core. */
  source: "vanilla" | "expansion",
  startUnlocked = false,
  researchCost = 40,
): TopicDef {
  return {
    id,
    name,
    homeGenre,
    source,
    compatibility: c(ranks),
    researchCost: startUnlocked ? 0 : researchCost,
    startUnlocked,
  };
}

export const TOPICS: TopicDef[] = [
  t("airplane", "Airplane", "action", ["action", "simulation", "strategy", "adventure", "casual", "rpg"], "vanilla", false, 40),
  t("aliens", "Aliens", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("archery", "Archery", "action", ["action", "simulation", "adventure", "rpg", "strategy", "casual"], "vanilla", false, 40),
  t("assassin", "Assassin", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("athletics", "Athletics", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("beat_em_up", "Beat-em-up", "action", ["action", "rpg", "adventure", "casual", "strategy", "simulation"], "vanilla", false, 40),
  t("biathlon", "Biathlon", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("bobsleigh", "Bobsleigh", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("canoeing", "Canoeing", "action", ["action", "simulation", "adventure", "casual", "strategy", "rpg"], "vanilla", false, 40),
  t("cycling", "Cycling", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("e_sports", "E-Sports", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("extreme_sports", "Extreme Sports", "action", ["action", "simulation", "casual", "adventure", "strategy", "rpg"], "vanilla", false, 40),
  t("football", "Football", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("formula_1", "Formula 1", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("hacking", "Hacking", "action", ["action", "strategy", "adventure", "rpg", "simulation", "casual"], "vanilla", false, 40),
  t("hockey", "Hockey", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("hunting", "Hunting", "action", ["action", "simulation", "adventure", "rpg", "strategy", "casual"], "vanilla", false, 40),
  t("ice_hockey", "Ice Hockey", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("judo", "Judo", "action", ["action", "rpg", "adventure", "simulation", "casual", "strategy"], "vanilla", false, 40),
  t("karate", "Karate", "action", ["action", "rpg", "adventure", "simulation", "casual", "strategy"], "vanilla", false, 40),
  t("martial_arts", "Martial Arts", "action", ["action", "rpg", "adventure", "simulation", "casual", "strategy"], "vanilla", false, 40),
  t("military", "Military", "action", ["action", "strategy", "simulation", "adventure", "rpg", "casual"], "vanilla", false, 40),
  t("motocross", "Motocross", "action", ["action", "simulation", "casual", "adventure", "strategy", "rpg"], "vanilla", false, 40),
  t("ninja", "Ninja", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("parkour", "Parkour", "action", ["action", "adventure", "casual", "simulation", "rpg", "strategy"], "vanilla", false, 40),
  t("police", "Police", "action", ["action", "adventure", "simulation", "strategy", "rpg", "casual"], "vanilla", false, 40),
  t("racing", "Racing", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", true, 40),
  t("rugby", "Rugby", "action", ["action", "simulation", "strategy", "casual", "adventure", "rpg"], "vanilla", false, 40),
  t("samurais", "Samurais", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("skiing", "Skiing", "action", ["action", "simulation", "casual", "adventure", "strategy", "rpg"], "vanilla", false, 40),
  t("sports", "Sports", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("spy", "Spy", "action", ["action", "adventure", "strategy", "rpg", "simulation", "casual"], "vanilla", false, 40),
  t("superheroes", "Superheroes", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("super_villain", "Super Villain", "action", ["action", "strategy", "adventure", "rpg", "simulation", "casual"], "vanilla", false, 40),
  t("surfing", "Surfing", "action", ["action", "simulation", "casual", "adventure", "strategy", "rpg"], "vanilla", false, 40),
  t("swimming", "Swimming", "action", ["action", "simulation", "casual", "adventure", "strategy", "rpg"], "vanilla", false, 40),
  t("table_tennis", "Table Tennis", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("tennis", "Tennis", "action", ["action", "simulation", "casual", "strategy", "adventure", "rpg"], "vanilla", false, 40),
  t("thief", "Thief", "action", ["action", "adventure", "strategy", "rpg", "simulation", "casual"], "vanilla", false, 40),
  t("ufo", "UFO", "action", ["action", "adventure", "strategy", "simulation", "rpg", "casual"], "vanilla", false, 40),
  t("werewolf", "Werewolf", "action", ["action", "rpg", "adventure", "simulation", "strategy", "casual"], "vanilla", false, 40),
  t("wild_west", "Wild West", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("wrestling", "Wrestling", "action", ["action", "simulation", "casual", "rpg", "strategy", "adventure"], "vanilla", false, 40),
  t("zombies", "Zombies", "action", ["action", "adventure", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 40),
  t("alternate_history", "Alternate History", "adventure", ["adventure", "strategy", "rpg", "simulation", "action", "casual"], "vanilla", false, 45),
  t("alternate_world", "Alternate World", "adventure", ["adventure", "rpg", "strategy", "action", "simulation", "casual"], "vanilla", false, 45),
  t("astronaut", "Astronaut", "adventure", ["adventure", "simulation", "action", "strategy", "rpg", "casual"], "vanilla", false, 45),
  t("cavemen", "Cavemen", "adventure", ["adventure", "action", "rpg", "simulation", "strategy", "casual"], "vanilla", false, 45),
  t("comedy", "Comedy", "adventure", ["adventure", "casual", "simulation", "action", "rpg", "strategy"], "vanilla", false, 45),
  t("crime", "Crime", "adventure", ["adventure", "action", "strategy", "simulation", "rpg", "casual"], "vanilla", false, 45),
  t("cyberpunk", "Cyberpunk", "adventure", ["adventure", "rpg", "action", "strategy", "simulation", "casual"], "vanilla", false, 45),
  t("dark_fantasy", "Dark Fantasy", "adventure", ["adventure", "rpg", "action", "strategy", "simulation", "casual"], "vanilla", false, 45),
  t("demons", "Demons", "adventure", ["adventure", "rpg", "action", "strategy", "simulation", "casual"], "vanilla", false, 45),
  t("detective", "Detective", "adventure", ["adventure", "strategy", "simulation", "rpg", "action", "casual"], "vanilla", false, 45),
  t("dinosaurs", "Dinosaurs", "adventure", ["adventure", "action", "simulation", "rpg", "strategy", "casual"], "vanilla", false, 45),
  t("doomsday", "Doomsday", "adventure", ["adventure", "action", "strategy", "simulation", "rpg", "casual"], "vanilla", false, 45),
  t("dystopian", "Dystopian", "adventure", ["adventure", "rpg", "strategy", "action", "simulation", "casual"], "vanilla", false, 45),
  t("expedition", "Expedition", "adventure", ["adventure", "simulation", "action", "strategy", "rpg", "casual"], "vanilla", false, 45),
  t("fairy_tale", "Fairy Tale", "adventure", ["adventure", "rpg", "casual", "strategy", "simulation", "action"], "vanilla", false, 45),
  t("ghosts", "Ghosts", "adventure", ["adventure", "rpg", "action", "casual", "strategy", "simulation"], "vanilla", false, 45),
  t("goblin", "Goblin", "adventure", ["adventure", "rpg", "action", "strategy", "casual", "simulation"], "vanilla", false, 45),
  t("hide_and_seek", "Hide and Seek", "adventure", ["adventure", "casual", "strategy", "action", "simulation", "rpg"], "vanilla", false, 45),
  t("history", "History", "adventure", ["adventure", "strategy", "simulation", "rpg", "action", "casual"], "vanilla", false, 45),
  t("horror", "Horror", "adventure", ["adventure", "action", "rpg", "simulation", "strategy", "casual"], "vanilla", false, 45),
  t("mummies", "Mummies", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "vanilla", false, 45),
  t("mystery", "Mystery", "adventure", ["adventure", "strategy", "rpg", "simulation", "action", "casual"], "vanilla", false, 45),
  t("pirate", "Pirate", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "expansion", false, 45),
  t("point_and_click", "Point & Click", "adventure", ["adventure", "strategy", "rpg", "casual", "simulation", "action"], "expansion", false, 45),
  t("post_apocalyptic", "Post-Apocalyptic", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "expansion", false, 45),
  t("prison", "Prison", "adventure", ["adventure", "simulation", "strategy", "action", "rpg", "casual"], "expansion", false, 45),
  t("romance", "Romance", "adventure", ["adventure", "simulation", "casual", "rpg", "strategy", "action"], "expansion", false, 45),
  t("sci_fi", "Sci-Fi", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "expansion", false, 45),
  t("space", "Space", "adventure", ["adventure", "action", "strategy", "simulation", "rpg", "casual"], "expansion", true, 45),
  t("steampunk", "Steampunk", "adventure", ["adventure", "rpg", "action", "strategy", "simulation", "casual"], "expansion", false, 45),
  t("survival", "Survival", "adventure", ["adventure", "action", "simulation", "strategy", "rpg", "casual"], "expansion", false, 45),
  t("time_travel", "Time Travel", "adventure", ["adventure", "rpg", "strategy", "simulation", "action", "casual"], "expansion", false, 45),
  t("vikings", "Vikings", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "expansion", false, 45),
  t("dungeon", "Dungeon", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", true, 50),
  t("evolution", "Evolution", "rpg", ["rpg", "simulation", "strategy", "adventure", "action", "casual"], "expansion", false, 50),
  t("fantasy", "Fantasy", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", true, 50),
  t("gods", "Gods", "rpg", ["rpg", "strategy", "adventure", "simulation", "action", "casual"], "expansion", false, 50),
  t("mad_science", "Mad Science", "rpg", ["rpg", "simulation", "strategy", "adventure", "action", "casual"], "expansion", false, 50),
  t("medieval", "Medieval", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", false, 50),
  t("mythology", "Mythology", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", false, 50),
  t("rage", "Rage", "rpg", ["rpg", "action", "adventure", "strategy", "simulation", "casual"], "expansion", false, 50),
  t("robot", "Robot", "rpg", ["rpg", "action", "simulation", "strategy", "adventure", "casual"], "expansion", false, 50),
  t("vampire", "Vampire", "rpg", ["rpg", "adventure", "action", "simulation", "strategy", "casual"], "expansion", false, 50),
  t("warlocks", "Warlocks", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", false, 50),
  t("witches", "Witches", "rpg", ["rpg", "adventure", "casual", "strategy", "simulation", "action"], "expansion", false, 50),
  t("wizards", "Wizards", "rpg", ["rpg", "adventure", "strategy", "action", "simulation", "casual"], "expansion", false, 50),
  t("business", "Business", "simulation", ["simulation", "strategy", "casual", "adventure", "action", "rpg"], "expansion", false, 45),
  t("city", "City", "simulation", ["simulation", "strategy", "adventure", "casual", "action", "rpg"], "expansion", false, 45),
  t("colonization", "Colonization", "simulation", ["simulation", "strategy", "adventure", "rpg", "action", "casual"], "expansion", false, 45),
  t("construction", "Construction", "simulation", ["simulation", "strategy", "casual", "adventure", "action", "rpg"], "expansion", false, 45),
  t("cooking", "Cooking", "simulation", ["simulation", "casual", "adventure", "strategy", "action", "rpg"], "expansion", false, 45),
  t("dance", "Dance", "simulation", ["simulation", "casual", "action", "adventure", "strategy", "rpg"], "expansion", false, 45),
  t("disasters", "Disasters", "simulation", ["simulation", "action", "strategy", "adventure", "rpg", "casual"], "expansion", false, 45),
  t("doctor", "Doctor", "simulation", ["simulation", "strategy", "adventure", "casual", "action", "rpg"], "expansion", false, 45),
  t("farming", "Farming", "simulation", ["simulation", "casual", "strategy", "adventure", "action", "rpg"], "expansion", false, 45),
  t("fashion", "Fashion", "simulation", ["simulation", "casual", "adventure", "strategy", "action", "rpg"], "expansion", false, 45),
  t("fishing", "Fishing", "simulation", ["simulation", "casual", "adventure", "action", "strategy", "rpg"], "expansion", false, 45),
  t("game_dev", "Game Dev", "simulation", ["simulation", "strategy", "casual", "adventure", "action", "rpg"], "expansion", false, 45),
  t("hospital", "Hospital", "simulation", ["simulation", "strategy", "adventure", "casual", "action", "rpg"], "expansion", false, 45),
  t("horse_racing", "Horse Racing", "simulation", ["simulation", "action", "casual", "strategy", "adventure", "rpg"], "expansion", false, 45),
  t("life", "Life", "simulation", ["simulation", "casual", "adventure", "strategy", "action", "rpg"], "expansion", false, 45),
  t("mining", "Mining", "simulation", ["simulation", "strategy", "adventure", "action", "rpg", "casual"], "expansion", false, 45),
  t("modern", "Modern", "simulation", ["simulation", "adventure", "strategy", "casual", "action", "rpg"], "expansion", false, 45),
  t("movies", "Movies", "simulation", ["simulation", "casual", "adventure", "strategy", "action", "rpg"], "expansion", false, 45),
  t("music", "Music", "simulation", ["simulation", "casual", "action", "adventure", "strategy", "rpg"], "expansion", false, 45),
  t("sailing", "Sailing", "simulation", ["simulation", "adventure", "casual", "action", "strategy", "rpg"], "expansion", false, 45),
  t("surgery", "Surgery", "simulation", ["simulation", "strategy", "action", "adventure", "casual", "rpg"], "expansion", false, 45),
  t("technology", "Technology", "simulation", ["simulation", "strategy", "adventure", "casual", "action", "rpg"], "expansion", false, 45),
  t("transport", "Transport", "simulation", ["simulation", "strategy", "adventure", "casual", "action", "rpg"], "expansion", false, 45),
  t("virtual_pet", "Virtual Pet", "simulation", ["simulation", "casual", "adventure", "strategy", "action", "rpg"], "expansion", false, 45),
  t("board_game", "Board Game", "strategy", ["strategy", "casual", "simulation", "adventure", "rpg", "action"], "expansion", false, 55),
  t("card_game", "Card Game", "strategy", ["strategy", "casual", "simulation", "rpg", "adventure", "action"], "expansion", false, 55),
  t("chess", "Chess", "strategy", ["strategy", "casual", "simulation", "adventure", "rpg", "action"], "expansion", false, 55),
  t("government", "Government", "strategy", ["strategy", "simulation", "adventure", "casual", "rpg", "action"], "expansion", false, 55),
  t("law", "Law", "strategy", ["strategy", "simulation", "adventure", "casual", "rpg", "action"], "expansion", false, 55),
  t("politics", "Politics", "strategy", ["strategy", "simulation", "adventure", "casual", "rpg", "action"], "expansion", false, 55),
  t("science", "Science", "strategy", ["strategy", "simulation", "rpg", "adventure", "casual", "action"], "expansion", false, 55),
  t("tower_defense", "Tower Defense", "strategy", ["strategy", "action", "simulation", "casual", "adventure", "rpg"], "expansion", false, 55),
  t("war", "War", "strategy", ["strategy", "action", "simulation", "adventure", "rpg", "casual"], "expansion", false, 55),
  t("abstract", "Abstract", "casual", ["casual", "simulation", "adventure", "strategy", "action", "rpg"], "expansion", false, 35),
  t("baking", "Baking", "casual", ["casual", "simulation", "adventure", "action", "strategy", "rpg"], "expansion", false, 35),
  t("educational", "Educational", "casual", ["casual", "simulation", "strategy", "adventure", "action", "rpg"], "expansion", false, 35),
  t("game_pack", "Game Pack", "casual", ["casual", "simulation", "strategy", "adventure", "action", "rpg"], "expansion", false, 35),
  t("maze", "Maze", "casual", ["casual", "adventure", "strategy", "simulation", "action", "rpg"], "expansion", false, 35),
  t("puzzle", "Puzzle", "casual", ["casual", "strategy", "simulation", "adventure", "action", "rpg"], "expansion", false, 35),
  t("rhythm", "Rhythm", "casual", ["casual", "simulation", "action", "adventure", "strategy", "rpg"], "expansion", false, 35),
  t("school", "School", "casual", ["casual", "simulation", "adventure", "strategy", "action", "rpg"], "expansion", false, 35),
  t("vocabulary", "Vocabulary", "casual", ["casual", "simulation", "strategy", "adventure", "action", "rpg"], "expansion", false, 35),
  // Media partnerships (Netflix-style licensed topics — original titles)
  t("media_orange_block", "Orange Block ★", "adventure", ["adventure", "rpg", "action", "strategy", "simulation", "casual"], "expansion", false, 80),
  t("media_squish_run", "Squish Run ★", "action", ["action", "casual", "adventure", "strategy", "rpg", "simulation"], "expansion", false, 90),
  t("media_crown_circuit", "Crown Circuit ★", "simulation", ["simulation", "strategy", "adventure", "casual", "rpg", "action"], "expansion", false, 85),
  t("media_stranger_pixels", "Stranger Pixels ★", "adventure", ["adventure", "action", "rpg", "strategy", "simulation", "casual"], "expansion", false, 85),
  t("media_witcher_ward", "Witcher Ward ★", "rpg", ["rpg", "adventure", "action", "strategy", "simulation", "casual"], "expansion", false, 95),
];

export const TOPIC_COUNT = TOPICS.length;

export function getTopicDef(id: string): TopicDef | undefined {
  return TOPICS.find((x) => x.id === id);
}

